f = sym('(x+1)*exp(x)');
a=0.4;
b=1;
n=8;
disp('Composite Rectangle Rule');
disp('Hasil integral dari f(x)=(x+1)*exp(x) dengan batas bawah 0.4 dan batas atas 1');
disp('Left End Point');
[E, result] = CompositeRectangleRule_LeftEndPoint(f,n,a,b);
disp(result);
disp('Dengan error Right End Point sekitar');
disp(E);
disp('Right End Point');
[E, result] = CompositeRectangleRule_RightEndPoint(f,n,a,b);
disp(result);
<<<<<<< HEAD
disp('Dengan error Left End Point sekitar');
disp(E);
disp('Mid End Point');
[E, result] = CompositeRectangleRule_MidEndPoint(f,n,a,b);
disp(result);
disp('Dengan error Mid End Point sekitar');
disp(E);
